use_frameworks!

platform :ios, '9.0'

target 'YHAlertController_Example' do
  pod 'YHAlertController', :path => '../'

  target 'YHAlertController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
